### ISSUE TITLE
Adapter#clear should only clear gate values

### ISSUE THREAD

**Issue by jnunemaker** [bgentry/flipper-activerecord#4]
It is documented as such, but I did not have a clear expectation in the test (since added here https://github.com/jnunemaker/flipper/pull/106). [This line](https://github.com/bgentry/flipper-activerecord/blob/cbdc8ab4ec57799343a6c8a9c2192f6bd87bc3d8/lib/flipper/adapters/activerecord.rb#L38) should only [clear the gates like this](https://github.com/jnunemaker/flipper/blob/4c6a9978940e0f7b097e51df153c4cac49f141c8/lib/flipper/adapters/active_record.rb#L66), not the entire feature, or you end up with behavior like this https://github.com/jnunemaker/flipper/issues/104 in the flipper UI.

**Comment by jnunemaker** [comment]
Forgot to link docs: 
https://github.com/jnunemaker/flipper/blob/2c07a8d0d1ddb15bf428a92faca0d2f6a6efa5f1/docs/Adapters.md#roll-your-own

**Comment by bgentry** [comment]
Thanks @jnunemaker, should have it resolved shortly with @trinode's PR #5
