### ISSUE TITLE
Get all features in one go

### ISSUE THREAD

**Issue by kenn** [bgentry/flipper-activerecord#6]
Every time when `enabled?` gets called, flipper makes multiple network round trips to the database.

Instead, we can get all features in one query and cache it during the same HTTP request-response cycle, so that following `enabled?` check will be done without hitting the database. It makes sense to most typical Rails apps.

This change has several implications and trade-offs between time and space at scale:

- The benefit of performance increases as the **average** number of features checked in a request grows.
  - Network RTT is becoming one of the slowest components in the tech stack. It takes at least 0.1ms in a fast 10GbE network, and it adds up linearly.
- The cost of memory increases as the **total** number of features grows.
  - 100 features shouldn't be a problem, but instantiating 1,000 AR objects might be debatable.
- An added bonus would be that it eliminates verbose multiple logs that calls flipper tables in development, which is basically a noise for the debugging purpose.

Would this be something we're interested in?

**Comment by bgentry** [comment]
@kenn hey, thanks for the idea. I just discovered that Flipper itself now has an AR adapter, so think this discussion would make more sense over there. I've asked in jnunemaker/flipper#207 whether I should just deprecate this gem and let people use the first-party adapter instead.

If I go forward with that, this is a great issue to open up on the main project as it affects other adapters too.

Cheers :beers:

**Comment by kenn** [comment]
Ohh, thanks for the heads up! Yeah I agree that it's the best if we could discuss it in the upstream. 👍

**Comment by jnunemaker** [comment]
@kenn @bgentry this was recently added in flipper. Adapters got a `get_multi` method and the DSL got a `preload` method which calls `get_multi`. The memoizing middlware then got a few options to preload specific feature or all of them. You can read more about it here:

https://github.com/jnunemaker/flipper/blob/dfdaa8265fe8ffc29666493663678d1fbc5bab87/docs/Optimization.md#memoizing-middleware

**Comment by jnunemaker** [comment]
Forgot to link up the related PR: https://github.com/jnunemaker/flipper/pull/198 and issue: https://github.com/jnunemaker/flipper/issues/206.

**Comment by bgentry** [comment]
ok, this project is now deprecated. Please use the AR adapter in the main project. Thanks! :v:

**Comment by kenn** [comment]
Awesome, thank you for the great work @bgentry and @jnunemaker !
